version: '3.8'

services:

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./gitea:/data
      - /var/log/gitea:/var/log/gitea
    networks:
      - internal
    expose:
      - "3000"
      - "22"

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - internal
    expose:
      - "3000"

  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    volumes:
      - ./authelia:/config
      - /var/log/authelia:/var/log/authelia
    networks:
      - internal
    expose:
      - "9091"
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - internal

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yaml
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - gitea
      - grafana
      - authelia
    networks:
      - internal

networks:
  internal:
    driver: bridge
