theme: dark
default_redirection_url: https://gitea.example.com

server:
  host: 0.0.0.0
  port: 9091

jwt_secret: 'your_secret_here'

authentication_backend:
  file:
    path: /config/users.yml

access_control:
  default_policy: deny
  rules:
    - domain: "*.example.com"
      policy: one_factor

session:
  name: authelia_session
  secret: 'another_secret'
  expiration: 3600
  inactivity: 300
  domain: example.com

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
