services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - "3001:3000"
    networks:
      - web

networks:
  web:
    external: true
